routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//get -> enviar datos de una pagina a otra
//post->enviar datos de un formulario a base de datos
//put ->actualizar un registro de base dedato
//delete->eliminar registro de base de datos
//update-> actualizar un registro
/*
Route::get('/proyecto/index','ProyectoController@index');
Route::get('/proyecto/create','ProyectoController@create');
Route::get('/proyecto/edit','ProyectoController@edit');
*/
// si no queremos trabajar uno por uno de las carptas, usaremos este metodo RESOURCE para agresar todas las rutas -> haremos eso en el crud
// no es necesario las lineas 23,24,25 por que el metodo resouce las remplaza todas.
// y no solo eso SI QUE LLAMARA A TODO LOS METODOS DE proyectiController,index,crete,store,edit...
Route::get('admin', function () {
    return view('admin.dashboard');
});
Route::resource('proyecto','ProyectoController');
Route::resource('Antecedente','AntecedenteController');
//juansbk_1

        /*el metodo view hace referencia a index que esta en proyecto */

app/Proyecto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
/* es un ORM */

class Proyecto extends Model
{
    //
    protected $table="dbo.Proyecto";//CONEXION CON LA BASE DE DATOS
    public $timestamps=false;
}

app/Http/Controllers/ProyectoController.php
<?php
/* estos metodos mos ayudara para hace las 
instrucciones e interactuar los datos de 
la base de datos */
namespace App\Http\Controllers;

use App\Proyecto;
use Illuminate\Http\Request;

class ProyectoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $lis_proyectos = Proyecto::get();//select * from table 
        //dd($lis_proyectos);// saber que volor tiene essa variable
        //pritf log
        return view('proyecto.index',compact('lis_proyectos'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('proyecto.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       //dd($request->all());

        $proy = new Proyecto;
        $proy->titu_proy = $request->titu_proy;
        $proy->justi_proy = $request->justi_proy;
        $proy->ambi_proy = $request->ambi_proy;
        $proy->pobla_proy = $request->pobla_proy;
        $proy->dirig_proy = $request->dirig_proy;
        $proy->doc_val_proy = $request->doc_val_proy;
        $proy->presu_proy = $request->presu_proy;
        $proy->metod_proy = $request->metod_proy;
        $proy->eje_proy = $request->eje_proy ;
        $proy->fe_ini_proy = $request->fe_ini_proy;
        $proy->fe_fin_proy = $request->fe_fin_proy;
        $proy->diag_proy = $request->diag_proy;
        $proy->resul_proy = $request->resul_proy;
        

        $proy->save();
        // $datosProyecto=request()->all();
      // $this->validate;  
      // $datosProyecto=request()->except("_token");
       // Proyecto::insert($datosProyecto);

        //return response()->json($datosProyecto);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function show(Proyecto $proyecto)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function edit(Proyecto $proyecto)
    {
        
        return view('Proyecto.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Proyecto $proyecto)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Proyecto $proyecto)
    {
        //
    }
}

resources/views/proyecto/create.blade.php
boton para crear nuevos proyectos
<form action="{{route('proyecto.store')}}" method="post" enctype="multipart/form-data">
{{ csrf_field() }}
<!-- imprime una llave de acceso para que cuando nostros hagamos el envio a 
estorage nos deje entrar gracias a que tenemos a esta llave -->

<label for="titu_proy">titu_proy</label>
<input type="text" name ="titu_proy" id= "titu_proy">
<br>

<label for="justi_proy">justi_proy</label>
<input type="text" name ="justi_proy" id= "justi_proy">
<br>

<label for="ambi_proy">ambi_proy</label>
<input type="text" name ="ambi_proy" id= "ambi_proy">
<br>

<label for="pobla_proy">pobla_proy</label>
<input type="text" name ="pobla_proy" id= "pobla_proy">
<br>

<label for="dirig_proy">dirig_proy</label>
<input type="text" name ="dirig_proy" id= "dirig_proy">
<br>

<label for="doc_val_proy">doc_val_proy</label>
<input type="text" name ="doc_val_proy" id= "doc_val_proy">
<br>

<label for="presu_proy">presu_proy</label>
<input type="text" name ="presu_proy" id= "presu_proy">
<br>
<label for="metod_proy">metod_proy</label>
<input type="text" name ="metod_proy" id= "metod_proy">
<br>
<label for="eje_proy">eje_proy</label>
<input type="text" name ="eje_proy" id= "eje_proy">
<br>
<label for="fe_ini_proy">fe_ini_proy</label>
<input type="date" name ="fe_ini_proy" id= "fe_ini_proy">
<br>
<label for="fe_fin_proy">fe_fin_proy</label>
<input type="date" name ="fe_fin_proy" id= "fe_fin_proy">
<br>
<label for="diag_proy">diag_proy</label>
<input type="text" name ="diag_proy" id= "diag_proy">
<br>
<label for="resul_proy">resul_proy</label>
<input type="text" name ="resul_proy" id= "resul_proy">
<br> 

<input type="submit"  value="Agregar">

</form>

resources/views/proyecto/edit.blade.php
boton para editar  algun proyecto

resources/views/proyecto/form.blade.php
formulario lado de la vista del proyecto para mostrar
tendra el formulario  de create y edit
 

resources/views/proyecto/index.blade.php
data central  o intefaz
inicio (despliegue de datos)



@foreach($lis_proyectos as $list)

<p>this is proyecto {{$list->cod_proy}}</p>



@endforeach

<a href="{{route ('proyecto.create')}}"> Crear</a>